# -*- coding: utf-8 -*-
"""helper_functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UWBwPhtX2TmNgMk3Z-R2bxuTkK_uun6D
"""

# Import dependencies
import torch
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split

# Standard PyTorch imports
import torch
from torch import nn

# Make device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

def accuracy(y_pred,y_true,device: torch.device=device):
  y_pred=y_pred.to(device)
  y_true=y_true.to(device)
  correct=torch.eq(y_true,y_pred).sum().item()
  acc=correct*100/len(y_pred)
  return acc

